environment: dev
replicaCount: 1
image:
  repository: image-registry.openshift-image-registry.svc:5000/checkout-frontend-ci/checkout-frontend
  tag: "b58897d1-6fd0-49bb-b55c-d36323d2d54a"
service:
  type: ClusterIP
  port: 80
  targetPort: 3000 # Geralmente Node/React roda na 3000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi
