environment: prod
ambiente: prod
replicaCount: 3 # Alta disponibilidade em Prod
image:
  repository: default-route-openshift-image-registry.apps.jmbquzwd.eastus.aroapp.io/checkout-frontend-ci/checkout-frontend
  tag: "b58897d1-6fd0-49bb-b55c-d36323d2d54a" # Tag imutável para produção
service:
  type: ClusterIP
  port: 8080
  targetPort: 3000
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
