environment: dev
replicaCount: 1
image:
  repository: image-registry.openshift-image-registry.svc:5000/pagamentos-api-ci/pagamentos-api
  tag: "12e9666f-fdf8-4218-9c01-dba68d8e1c79"
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
