environment: production
replicaCount: 3 # Alta disponibilidade em Prod
image:
  repository: quay.io/sua-org/pagamentos-api
  tag: "v1.0.0" # Tag imutável para produção
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
