apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  port:
    targetPort: {{ .Values.service.targetPort }}
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
  wildcardPolicy: None
